version: "3.7"

services:
  app:
    build: . #path to the root project folder
    command: python reverse_proxy.py
    volumes:
      - .:/reverse_proxy
    ports:
      - 8080:8080 # sets the port that maps to internal port in docker container